import { StyleSheet } from "react-native";
import { colors, spacing, radius } from "@/src/theme";

export const styles = StyleSheet.create({
  topHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.md,
  },
  eyebrow: {
    fontSize: 12,
    color: colors.brandSecondary,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  h1: {
    fontSize: 26,
    fontWeight: "800",
    color: colors.onSurface,
    marginTop: 2,
  },
  syncIconButton: {
    width: 38,
    height: 38,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceSecondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },

  // Visiting Card Styles
  cardContainer: {
    borderRadius: radius.lg,
    padding: spacing.lg,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  cardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  merchantBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radius.pill,
  },
  merchantBadgeText: {
    color: "#F8FAFC",
    fontSize: 12,
    fontWeight: "700",
  },
  editCardBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(255, 255, 255, 0.16)",
    paddingHorizontal: spacing.md,
    minHeight: 32,
    borderRadius: radius.pill,
  },
  editCardBtnText: {
    color: "#E0F2F1",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  cardMain: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.md,
    marginTop: spacing.md,
  },
  cardShopName: {
    fontSize: 20,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: 0.3,
  },
  cardOwnerName: {
    fontSize: 13,
    fontWeight: "600",
    color: "#B2DFDB",
    marginTop: 2,
  },
  cardDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 4,
  },
  cardDetailText: {
    fontSize: 12,
    color: "#E0F2F1",
    fontWeight: "500",
  },
  cardAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 2,
    borderColor: "#F8FAFC",
  },
  cardAvatarFallback: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#B2DFDB",
  },
  cardAvatarInitials: {
    fontSize: 22,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  upiPill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: radius.sm,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginTop: spacing.md,
  },
  upiPillLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
  },
  upiPillText: {
    color: "#E0F2F1",
    fontSize: 12,
  },
  upiPillBold: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  upiCopyBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingHorizontal: spacing.md,
    minHeight: 32,
    justifyContent: "center",
    borderRadius: radius.pill,
  },
  upiCopyText: {
    color: "#FFFFFF",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  cardActionsRow: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  cardPrimaryBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#F8FAFC",
    paddingVertical: 9,
    borderRadius: radius.md,
  },
  cardPrimaryBtnText: {
    color: colors.brandSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  cardSecondaryBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    paddingVertical: 9,
    borderRadius: radius.md,
  },
  cardSecondaryBtnText: {
    color: "#F8FAFC",
    fontSize: 12,
    fontWeight: "700",
  },

  balanceCard: {
    marginTop: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    backgroundColor: colors.surfaceSecondary,
    borderRadius: radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  balanceVal: { fontSize: 22, fontWeight: "800", color: colors.onSurface, marginVertical: 2 },

  openShopCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderColor: colors.brandPrimary,
    backgroundColor: colors.brandTertiary,
  },
  openShopIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.brandPrimary,
  },
  openShopTitle: { fontSize: 16, fontWeight: "800", color: colors.brandPrimary },
  openShopSub: { fontSize: 12, color: colors.onSurfaceSecondary, marginTop: 2 },
  closeShopLink: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: spacing.lg,
    paddingVertical: spacing.sm,
  },
  closeShopText: { fontSize: 13, fontWeight: "700", color: colors.error },

  // Persona Switcher
  personaContainer: {
    marginTop: spacing.lg,
    backgroundColor: colors.surfaceSecondary,
    borderRadius: radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionMiniLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.muted,
    textTransform: "uppercase",
    marginBottom: spacing.xs,
  },
  personaSwitchRow: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    padding: 3,
    borderWidth: 1,
    borderColor: colors.border,
  },
  personaSegment: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 9,
    borderRadius: radius.sm,
  },
  personaSegmentActive: {
    backgroundColor: colors.brandTertiary,
  },
  personaText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.muted,
  },
  personaTextActive: {
    color: colors.brandPrimary,
    fontWeight: "700",
  },
  personaHelper: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 6,
    lineHeight: 15,
  },

  // Analytics Section
  analyticsSection: {
    marginTop: spacing.xl,
  },
  analyticsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.xs,
  },
  healthChip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radius.pill,
  },
  healthChipGood: {
    backgroundColor: colors.successSoft,
  },
  healthChipAvg: {
    backgroundColor: "#FEF3C7",
  },
  healthChipLow: {
    backgroundColor: colors.errorSoft,
  },
  healthChipText: {
    fontSize: 12,
    fontWeight: "700",
  },
  healthTextGood: {
    color: colors.success,
  },
  healthTextAvg: {
    color: colors.warning,
  },
  healthTextLow: {
    color: colors.error,
  },
  analyticsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  analyticsCard: {
    flexBasis: "48%",
    flexGrow: 1,
    backgroundColor: colors.surfaceSecondary,
    borderRadius: radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  analyticsCardTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  analyticsLabel: {
    fontSize: 12,
    color: colors.muted,
    fontWeight: "600",
  },
  analyticsVal: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.onSurface,
    marginTop: 4,
  },
  analyticsSub: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 2,
  },
  progressBarWrapper: {
    marginTop: spacing.sm,
  },
  progressBarBackground: {
    height: 6,
    backgroundColor: colors.border,
    borderRadius: radius.pill,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: colors.success,
    borderRadius: radius.pill,
  },
  progressTextRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
  },
  progressSubText: {
    fontSize: 12,
    color: colors.muted,
  },

  // Sync Card
  syncCard: {
    flexDirection: "row",
    gap: spacing.md,
    alignItems: "center",
    padding: spacing.md,
    backgroundColor: colors.successSoft,
    borderRadius: radius.md,
    marginTop: spacing.lg,
  },
  syncTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.success,
  },
  syncSub: {
    fontSize: 12,
    color: colors.onSurfaceSecondary,
    marginTop: 2,
  },
  syncBtnSmall: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    backgroundColor: colors.surface,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.warning,
  },
  syncBtnSmallText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.warning,
  },

  // Settings Group
  groupHead: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.muted,
    textTransform: "uppercase",
    marginTop: spacing.xl,
    marginBottom: spacing.xs,
    letterSpacing: 0.5,
  },
  sectionHead: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.onSurface,
  },
  card: {
    backgroundColor: colors.surfaceSecondary,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    padding: spacing.md,
  },
  rowBorder: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  rowValue: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.onSurface,
  },
  rowLabel: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 2,
  },
  trashBadge: {
    backgroundColor: "#FEF3C7",
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: radius.pill,
  },
  trashBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.warning,
  },
  errorText: {
    color: colors.error,
    fontSize: 12,
    marginTop: spacing.xs,
  },

  // Logout
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    marginTop: spacing.xl,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.errorSoft,
    borderWidth: 1,
    borderColor: colors.border,
  },
  logoutText: {
    color: colors.error,
    fontSize: 14,
    fontWeight: "700",
  },

  syncLine: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginTop: spacing.md, marginBottom: spacing.md, paddingHorizontal: spacing.md, paddingVertical: 10, borderRadius: radius.md, backgroundColor: colors.successSoft },
  syncLineText: { flex: 1, fontSize: 12, fontWeight: "700" },
  syncLineAction: { fontSize: 12, fontWeight: "800" },
  meter: { marginTop: spacing.md, padding: spacing.sm, borderRadius: radius.sm, backgroundColor: "rgba(255, 255, 255, 0.12)" },
  meterHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  meterText: { fontSize: 12, fontWeight: "700", color: "#FFFFFF" },
  meterAction: { fontSize: 12, fontWeight: "800", color: "#F8FAFC" },
  meterTrack: { height: 5, borderRadius: 3, backgroundColor: "rgba(255, 255, 255, 0.15)", marginTop: 6, overflow: "hidden" },
  meterFill: { height: 5, borderRadius: 3, backgroundColor: "#FFFFFF" },
  miniSeg: { flexDirection: "row", backgroundColor: colors.surface, borderRadius: radius.pill, padding: 2, borderWidth: 1, borderColor: colors.border },
  miniSegBtn: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: radius.pill },
  miniSegOn: { backgroundColor: colors.brandPrimary },
  miniSegText: { fontSize: 12, fontWeight: "700", color: colors.muted },
  miniSegTextOn: { color: colors.onBrandPrimary },
  lockChips: { flexDirection: "row", flexWrap: "wrap", gap: 6, width: "100%", paddingLeft: 48 },
  lockChip: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  backupStatus: { flexDirection: "row", alignItems: "center", gap: spacing.sm, paddingHorizontal: spacing.md, paddingVertical: 10, backgroundColor: colors.successSoft },
  backupStatusText: { flex: 1, fontSize: 12, fontWeight: "700" },
  dangerZone: { marginTop: spacing.xl, borderWidth: 1, borderColor: colors.error, borderRadius: radius.md, padding: spacing.md, backgroundColor: "#FFF7F6" },
  dangerHead: { fontSize: 12, fontWeight: "800", color: colors.error, letterSpacing: 0.5, marginBottom: spacing.xs },
  dangerRow: { flexDirection: "row", alignItems: "center", gap: spacing.md, paddingVertical: spacing.xs },

  // Footer
  footerWrap: {
    alignItems: "center",
    marginTop: spacing.xl,
    paddingBottom: spacing.md,
  },
  footerBrand: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.muted,
  },
  footerSub: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 2,
  },
});
